### ISSUE TITLE
Strange error when sum_type macro is used inside a begin block

### ISSUE THREAD

**Issue by Tortar** [MasonProtter/SumTypes.jl#67]
For non-parametric sum types this works fine

```julia
julia> using SumTypes

julia> begin
           mutable struct A
               x::Int
           end
           @sum_type B begin
               C(a::A)
           end
       end
```

but when you try with a parametric one a strange error with no informative stacktrace appears:

```julia
julia> using SumTypes

julia> begin
           mutable struct A{X}
               x::X
           end
           @sum_type B{X} begin
               C{X}(a::A{X})
           end
       end
ERROR: syntax: SlotNumber objects should not occur in an AST
Stacktrace:
 [1] top-level scope
   @ REPL[2]:1
 [2] top-level scope
   @ REPL[2]:5
```

**Comment by Tortar** [comment]
This works fine instead

```julia
julia> using SumTypes

julia> begin
           mutable struct A{Y}
               x::Y
           end
           @sum_type B{X} begin
               C{X}(a::A{X})
           end
       end
```

so the workaround is simple, but I'm puzzled by what Julia gets confused

**Comment by MasonProtter** [comment]
I'm guessing this is because SumTypes emits an `Expr(:toplevel, ...)` object instead of an `Expr(:block, ...)` for the struct definition. There's some kinda scary edge cases with macros defining structs, but since the implementation of sumtypes has changed a lot, maybe we no longer need to use `Expr(:toplevel)` and can go back to `Expr(:block)`.
